FROM nginx:alpine

# www-dataグループとユーザーの存在を確認して、存在しない場合にのみ作成
RUN addgroup -S www-data || true && adduser -S www-data -G www-data || true

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/fastcgi-php.conf /etc/nginx/snippets/fastcgi-php.conf
